import sys
import os

from pydub import AudioSegment
#-------------------------------------------------------------------------------

if len(sys.argv) < 2:
    print()
    print('Usage: python convert_audio.py input.mp3 [output_name]')
    print()
    sys.exit(1)
#-------------------------------------------------------------------------------

def convert_mp3(input_file, output_file):
    audio = AudioSegment.from_mp3(input_file) \
                        .set_channels(1)      \
                        .set_frame_rate(48828)

    audio.export(output_file, format='wav', codec='pcm_s16le')
    print(f'Saved converted audio to: {output_file}')

    return audio.get_array_of_samples()
#-------------------------------------------------------------------------------

def trim(data):
    start = 0
    while start < len(data) and data[start] == 0:
        start += 1

    end = len(data)
    while end > start and data[end-1] == 0:
        end -= 1

    return data[start:end]
#-------------------------------------------------------------------------------

input_file  = sys.argv[1]
output_file = sys.argv[2] if len(sys.argv) > 2 else os.path.splitext(input_file)[0]

samples = trim(convert_mp3(input_file, output_file+'.wav'))

abs_samples = [ abs(s) for s in samples ]
print(f'Samples        = {len(abs_samples)}')
print(f'Mean amplitude = {sum(abs_samples) / len(abs_samples)}')
print(f'Max  amplitude = {max(abs_samples)}')
#-------------------------------------------------------------------------------

with open(output_file+'.mif', 'w', newline='\n', encoding='utf-8') as file:
    file.write(f'-- Generated by convert.py\n')
    file.write(f'-- Source: {input_file}\n')
    file.write(f'\n')
    file.write(f'DEPTH = {2**16};\n')
    file.write(f'WIDTH = 16;\n')
    file.write(f'ADDRESS_RADIX = HEX;\n')
    file.write(f'DATA_RADIX = DEC;\n')
    file.write(f'\n')
    file.write(f'CONTENT\n')
    file.write(f'BEGIN\n')
    for n, sample in enumerate(samples[0:2**16]):
        file.write(f'    {n:04X} : {sample};\n')
    file.write(f'END;\n')
#-------------------------------------------------------------------------------

while len(samples) < 2**25:
    samples.extend(samples)

if len(samples) > 2**25:
    samples = samples[0:2**25]

with open(output_file+'.dat', 'w', newline='\n', encoding='utf-8') as file:
    for sample in reversed(samples):
        if sample < 0:
            file.write(f'{sample+2**16:04X}')
        else:
            file.write(f'{sample:04X}')
#-------------------------------------------------------------------------------

