import numpy as np
import matplotlib.pyplot as plt

N  = 2048
fs = 100e6/1024

f = np.linspace(0, fs, N+1)
f = f[0:-1]
H = np.array([ 1 if x < 300 or x > (fs-300) else 0 for x in f ])

plt.figure()
plt.plot(f, H)
plt.xlabel("Frequency [Hz]")
plt.ylabel("Magnitude")
plt.title("H")
plt.grid(True)
plt.tight_layout()
#-------------------------------------------------------------------------------

h = np.real(np.fft.fftshift(np.fft.ifft(H)))

plt.figure()
plt.plot(h)
plt.xlabel("Point Index")
plt.ylabel("Magnitude")
plt.title("h")
plt.grid(True)
plt.tight_layout()
#-------------------------------------------------------------------------------

h *= np.hanning(N)
h /= np.sum(h)

plt.figure()
plt.plot(h)
plt.xlabel("Point Index")
plt.ylabel("Magnitude")
plt.title("h, windowed and normalised")
plt.grid(True)
plt.tight_layout()
#-------------------------------------------------------------------------------

f  = np.linspace(0, fs, 32*N+1)
f  = f[0:-1]
f -= f[16*N]
H = np.fft.fftshift(np.fft.fft(h, n=32*N))

plt.figure()
plt.plot(f, 20*np.log10(np.abs(H)))
plt.xlabel("Frequency [Hz]")
plt.ylabel("Magnitude")
plt.title("Filter response")
plt.grid(True)
plt.tight_layout()
#-------------------------------------------------------------------------------

scale = 1
while np.max(h) < 0.5:
    h     *= 2
    scale *= 2
print(f'scale = {scale}')

h = np.round(2**17 * h)
#-------------------------------------------------------------------------------

with open('Filter.mif', 'w', newline='\n', encoding='utf-8') as file:
    file.write(f'-- Generated by Filter.py\n')
    file.write(f'\n')
    file.write(f'DEPTH = {N};\n')
    file.write(f'WIDTH = 18;\n')
    file.write(f'ADDRESS_RADIX = HEX;\n')
    file.write(f'DATA_RADIX = HEX;\n')
    file.write(f'\n')
    file.write(f'CONTENT\n')
    file.write(f'BEGIN\n')
    for n, coef in enumerate(h):
        if coef < 0:
            file.write(f'    {n:03X} : {int(coef)+2**18:05X};\n')
        else:
            file.write(f'    {n:03X} : {int(coef):05X};\n')
    file.write(f'END;\n')
#-------------------------------------------------------------------------------

plt.show()
#-------------------------------------------------------------------------------
