from math import *

N  = 2**12
pi = 3.14159265358979324

with open('NCO.mif', 'w', newline='\n', encoding='utf-8') as file:
    file.write(f'-- Generated by NCO.py\n')
    file.write(f'\n')
    file.write(f'DEPTH = {N};\n')
    file.write(f'WIDTH = 9;\n')
    file.write(f'ADDRESS_RADIX = HEX;\n')
    file.write(f'DATA_RADIX = HEX;\n')
    file.write(f'\n')
    file.write(f'CONTENT\n')
    file.write(f'BEGIN\n')
    for n in range(N):
        x = round((2**8-1) * sin(2*pi * n/N))
        if x < 0:
            x += 2**9
        file.write(f'    {n:03X} : {x:03X};\n')
    file.write(f'END;\n')
#-------------------------------------------------------------------------------

